# Generated by Django 5.1.6 on 2025-02-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='image',
        ),
        migrations.AddField(
            model_name='postimage',
            name='file_name',
            field=models.CharField(default='not_found', max_length=255),
        ),
    ]
